/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "GoogleClientEmail": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GooglePrivateKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LinkSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SheetId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SiteUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}